---
name: Gradle

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Run commands
        run: |
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omero-ms-image-region_${{ matrix.java }}
          path: build/distributions/*

  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags') && github.repository_owner == 'ome'
    strategy:
      matrix:
        java: [11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts from build
        uses: actions/download-artifact@v4
      - name: List artifacts
        run: ls -R
      - name: Create a release and upload Release Assets
        run:  |
          cd ./omero-ms-image-region_${{ matrix.java }}
          sha256sum ./*.zip >> SHASUMS
          sha256sum ./*.tar >> SHASUMS
          tag_name="${GITHUB_REF##*/}"
          gh release create "$tag_name" ./*.zip ./*.tar SHASUMS
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
