---
name: Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Run commands
        run: |
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omero-ms-image-region_${{ matrix.java }}
          path: build/distributions/*
  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts from build
        uses: actions/download-artifact@v4
      - name: Create a release and upload Release Assets
        run:  |
          version=$(./gradlew properties | grep ^version:)
          tag=${GITHUB_REF#refs/*/}
          for file in */*
            do
              if [ -f "$file" ];then
                base=$(dirname $file)
                version="${base##*_}"
                filename=$(basename -- "$file")
                extension="${filename##*.}"
                name="${filename%.*}"
                newname="${name}_$version.${extension}"
                mv $file $newname
                sha256sum $newname >> SHASUMS
              fi
          done
          gh release create $tag *.zip *.tar SHASUMS --notes-from-tag
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
